### ISSUE TITLE
How to get vertices from persistent intervals?

### ISSUE THREAD

**Issue by khushboo810** [appliedtopology/javaplex#11]
Hi, I want to know the exact vertices which belong to a 1-D cycle.
Using the computeAnnotatedIntervals function, I am able to see all the cycle intervals and the edges. Below is an example:

```
int_generators = intervals.getIntervalGeneratorPairsAtDimension(1)
A_arr = int_generators.toArray;
temp1 = A_arr(1);
```

```
temp1:
[0.05625, 0.0625), [267,282] + [282,290] + [267,271] + [271,290])
```

Now I want to extract the vertices belonging to this cycle. In this example, it has four vertices. The chain belongs to class IntSparseFormalSum. Can someone please tell me how to parse the vertices from this cycle?

**Comment by petercrlane** [comment]
IntSparseFormalSum is in a different package, the source is at: https://github.com/ogdet/primitive-lib/blob/master/src/edu/stanford/math/primitivelib/autogen/formal_sum/IntSparseFormalSum.java
The sum is a set of key-value pairs: keys being the objects added, and value the coefficients.  In this case, the keys are Simplex instances.  To get all the vertices, you need to use the specialised iterator.

(I use neither Matlab nor Java, so this is Java-ish pseudo-code.)

intervals = persistence.computeAnnotatedIntervals stream()
dim-n = intervals.getGeneratorsAtDimension(n) // for generators at dimension n
// dim-n is an ArrayList of IntSparseFormalSum instances.

// You can get an iterator for the instance of IntSparseFormalSum, which works as follows:
it = dim-n.get(0).iterator ()  // to get the iterator for first item in list
while (it.hasNext ()) {
  it.advance();
  it.key ();  // is the current part of the addition, which is a Simplex (back in JavaPlex library)
  it.key().getVertices (); // returns an int[] of the vertices
  it.value() // is the coefficient in the sum
}
