### ISSUE TITLE
Update the `load_javaplex.m` file

### ISSUE THREAD

**Issue by michiexile** [appliedtopology/javaplex#12]
It seems like changes for Matlab2016a broke the way `load_javaplex.m` worked. We should update the file so it works out of the box.

One culprit seems to be `clear import`.

**Comment by henryadams** [comment]
I think the changes we need to make are as follows:

(1) In load_javaplex.m, comment out line 4 which says
clear import;

(2) After running load_javaplex.m, type
>> import edu.stanford.math.plex4.*;
into the Matlab command window.

(However, I haven't yet tested these myself)

Best, Henry

**Comment by henryadams** [comment]
I have added a new version of Javaplex, version 4.2.6, which should now easily support installation with Matlab 2016. The changes are as in (1) and (2) of my previous post of this thread. The tutorial instructions have been updated as well. I am marking this issue as closed, but please let me know if you have any trouble running Javaplex in newer versions of Matlab!
