### ISSUE TITLE
Mapper Algorithm

### ISSUE THREAD

**Issue by shivin9** [appliedtopology/javaplex#13]
Hi,

I want to know whether you have implemented the Mapper algorithm in javaplex.
I am new to TDA and am exploring this field so can anyone tell what is the essential use of persistent homology in the Mapper algorithm. Furthermore, how can persistence homology be separately used to analyze and visualize datasets.

Thanks
Shivin

**Comment by henryadams** [comment]
Hi Shivin,

It looks like Mapper has been implemented in javaplex. Indeed, see the following links:
https://github.com/appliedtopology/javaplex/tree/master/src/java/edu/stanford/math/mapper
http://appliedtopology.github.io/javaplex/doc/index.html?edu/stanford/math/mapper/
https://github.com/appliedtopology/javaplex/tree/master/src_test/java/edu/stanford/math/mapper
That being said, I've never used Mapper in Javaplex. Has anybody here used Mapper in Javaplex?

Persistent homology and mapper are two completely distinct algorithms -- neither one is used in the other.

Best, Henry

**Comment by kleinthetopologist** [comment]
I must admit, I had no idea that we _had_ Mapper in JavaPlex. I should check it out.

Mikael Vejdemo-Johansson
mikael@appliedtopology.org
http://atmcs.appliedtopology.org <http://atmcs.appliedtopology.org/>

**Comment by shivin9** [comment]
Hi @henryadams,

Thanks for pointing that out for me. Actually I am planning to implement a data analysis tool in Julia which uses the Mapper algorithm. So just wanted to clarify on that.
BTW are you aware of Ayasdi and their software Ayasdi Core? Do you have any idea as to how they mix Machine Learning and TDA to create revealing summaries of data. There seem to be no experts in this area of Machine Learning.

Thanks,
Shivin

**Comment by henryadams** [comment]
Hi Shivin,

I do know about Ayasdi and Ayasdi Core. Many people have thought about mixing TDA with machine learning, and written papers along these lines. But this is still very much a wide open area, and I don't know the specific details of the techniques Ayasdi tries.

Best, Henry
