### ISSUE TITLE
The Betti Numbers

### ISSUE THREAD

**Issue by khairyah** [appliedtopology/javaplex#14]
Hi,

I just to ask, what is the purpose of using the betti numbers in this paper?
And what can we  interpret based on the barcode that we get from the betti numbers?

Thank you.

Khairyah

**Comment by petercrlane** [comment]
Take a look at page 19 of the tutorial.  The barcodes show us the dataset has Betti numbers: [1, 2, 1]  Notice the Betti numbers are only counted based on the arrows leaving the right-side of the barcode plot: there are other lines on the barcode plot, but those do not persist, and so are not Betti numbers.

Interpreting the [1, 2, 1] The first 1 tells us we have a single component, the 2 tells us there are two 1D loops, and the last 1 tells us there is a 2D region enclosed by the surface.  If we were just given the point data, we now have some useful information: that the data are located along a Torus.  

Section 6 does this kind of investigation on more complex data where we do not know the structure in advance.  The results help us understand the data better.
