### ISSUE TITLE
How to build a stream(simplex) from a graph or a network(Adjacency Matrix)

### ISSUE THREAD

**Issue by Wangxingdong** [appliedtopology/javaplex#18]

**Comment by henryadams** [comment]
One option is to build an explicit metric space where the distance between any two vertices in the graph is the length of the shortest path between them. Then build the Vietoris-Rips complex on top of this explicit metric space.

**Comment by henryadams** [comment]
If you come up with any other definitions, then you can build them as simplicial complexes using the Explicit Simplex Stream class.

**Comment by Wangxingdong** [comment]
Thank you for your answer,  still I have some questions and I hope you can help me.

[Seek help for simplicial complex understanding.docx](https://github.com/appliedtopology/javaplex/files/1834260/Seek.help.for.simplicial.complex.understanding.docx)
@henryadams 
![seek help for simplicial complex understanding](https://user-images.githubusercontent.com/37624901/37724384-9403b5bc-2d6b-11e8-938d-4ffa72694d41.GIF)
Sincerely thank you！

**Comment by kleinthetopologist** [comment]
In both of these examples, you have 4 (and 6) «minimal» cycles -- the triangles in the tetrahedron, the sides of the cube. 

One of these cycles can be expressed in terms of the other 3 (or 5), and so does not contribute any essential cycles to the homology.

For the tetrahedron, your four minimal cycles are 
[1,2] + [2,3] + [1,3]
[1,2] + [2,4] + [1,4]
[1,3] + [3,4] + [1,4]
[2,3] + [3,4] + [2,4]

(written in order as you go around the cycle)

Notice here (and remember that we are working mod 2) that 
([1,2] + [2,3] + [1,3]) + 
([1,2] + [2,4] + [1,4]) + 
([1,3] + [3,4] + [1,4]) =
[1,2] + [1,2] + [1,3] + [1,3] + [1,4] + [1,4] + [2,3] + [3,4] + [2,4] = 
[2,3] + [3,4] + [2,4]

So the last can be expressed in terms of the others, and is left out when reporting the results of the computation.

Mikael Vejdemo-Johansson
mikael@appliedtopology.org
http://atmcs.appliedtopology.org <http://atmcs.appliedtopology.org/>
