### ISSUE TITLE
Time Complexity of function

### ISSUE THREAD

**Issue by suravi2016** [appliedtopology/javaplex#20]
I want to know the time complexity of the createVietorisRipsStream, getModularSimplicialAlgorithm
   and persistence.computeIntervals(stream) functions.

**Comment by henryadams** [comment]
The algorithm to compute persistent homology (say getModularSimplicialAlgorithm
and persistence.computeIntervals(stream)) is at worst cubic in the number of simplices. Building a Vietoris-Rips simplicial complex can be at worst exponential in the number of vertices, as the complete simplicial complex on n vertices has 2^n-1 simplices. That is why one must limit the size of a Vietoris-Rips simplicial complex construction.
