### ISSUE TITLE
How to evaluate large data sets?

### ISSUE THREAD

**Issue by pengwang123** [appliedtopology/javaplex#22]
hi, I tried to evaluate few hundred images with the tool box, but it seems the tool box can't work on larger size data. Did I make any mistake?
Thanks!

**Comment by henryadams** [comment]
See the warning on page 13 of the tutorial (http://www.math.colostate.edu/~adams/research/javaplex_tutorial.pdf): If you try to build the largest possible simplicial complex on only 266 vertices, then the number of simplices you build is on the order of the number of atoms in the universe. This is why you must set the max filtration value small, as described in that warning, and then increase it gradually. You may also be interested in witness complexes. You may also be interested in other software packages that are designed more for large computations, as described in Section 1.1 of the tutorial.
