### ISSUE TITLE
Where is javaplex-4.1.0.jar?

### ISSUE THREAD

**Issue by ChristianKKelley** [appliedtopology/javaplex#28]
In the [interoperability section](https://github.com/appliedtopology/javaplex/wiki/Interoperability) for Java, it says to download the file javaplex-4.1.0.jar.  Where is this file?

**Comment by michiexile** [comment]
I have edited the interoperability section to clarify, and I am investigating our release processes to see why we stopped releasing the JAR-file as a separate asset.

You can find the most recent releases here: https://github.com/appliedtopology/javaplex/releases/ 
And within these releases, the `javaplex.jar` that you need is distributed in both the `matlab_examples` file inside the `lib` directory and in the `javaplex-processing-lib` file inside the `library` directory.
